// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PageBE.DataModel;

namespace PageBE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230316182657_PrvaMigracija")]
    partial class PrvaMigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PageBE.DataModel.Kurs", b =>
                {
                    b.Property<int>("kursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivKursa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("kursId");

                    b.ToTable("Kurs");

                    b.HasData(
                        new
                        {
                            kursId = 1,
                            NazivKursa = "Web Programiranje"
                        },
                        new
                        {
                            kursId = 2,
                            NazivKursa = "RWA"
                        },
                        new
                        {
                            kursId = 3,
                            NazivKursa = "ISMO"
                        },
                        new
                        {
                            kursId = 4,
                            NazivKursa = "IS"
                        });
                });

            modelBuilder.Entity("PageBE.DataModel.KursStudenta", b =>
                {
                    b.Property<int>("kursStudentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("kursId")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.HasKey("kursStudentaId");

                    b.HasIndex("kursId");

                    b.HasIndex("studentId");

                    b.ToTable("KursStudentas");

                    b.HasData(
                        new
                        {
                            kursStudentaId = 1,
                            kursId = 3,
                            studentId = 3
                        },
                        new
                        {
                            kursStudentaId = 2,
                            kursId = 2,
                            studentId = 1
                        },
                        new
                        {
                            kursStudentaId = 3,
                            kursId = 1,
                            studentId = 2
                        });
                });

            modelBuilder.Entity("PageBE.DataModel.StatusStudenta", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivStatusa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("statusId");

                    b.ToTable("statusStudentas");

                    b.HasData(
                        new
                        {
                            statusId = 1,
                            NazivStatusa = "Redovan"
                        },
                        new
                        {
                            statusId = 2,
                            NazivStatusa = "Vanredan"
                        });
                });

            modelBuilder.Entity("PageBE.DataModel.Studenti", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StatusStudentastatusId")
                        .HasColumnType("int");

                    b.Property<int>("brojIndexa")
                        .HasColumnType("int");

                    b.Property<int?>("statusId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("studentId");

                    b.HasIndex("StatusStudentastatusId");

                    b.ToTable("Studentis");

                    b.HasData(
                        new
                        {
                            studentId = 1,
                            Godina = 3,
                            Ime = "Ime 1",
                            Prezime = "Nakon Seeda",
                            brojIndexa = 1111,
                            statusId = 1
                        },
                        new
                        {
                            studentId = 2,
                            Godina = 1,
                            Ime = "Ime 2",
                            Prezime = "Nakon Seeda",
                            brojIndexa = 1221,
                            statusId = 2
                        },
                        new
                        {
                            studentId = 3,
                            Godina = 2,
                            Ime = "Ime 3",
                            Prezime = "Nakon Seeda",
                            brojIndexa = 13331,
                            statusId = 1
                        });
                });

            modelBuilder.Entity("PageBE.DataModel.KursStudenta", b =>
                {
                    b.HasOne("PageBE.DataModel.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("kursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PageBE.DataModel.Studenti", "Studentis")
                        .WithMany()
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Studentis");
                });

            modelBuilder.Entity("PageBE.DataModel.Studenti", b =>
                {
                    b.HasOne("PageBE.DataModel.StatusStudenta", "StatusStudenta")
                        .WithMany("Studentis")
                        .HasForeignKey("StatusStudentastatusId");

                    b.Navigation("StatusStudenta");
                });

            modelBuilder.Entity("PageBE.DataModel.StatusStudenta", b =>
                {
                    b.Navigation("Studentis");
                });
#pragma warning restore 612, 618
        }
    }
}
